### ISSUE TITLE
AssertionError: Already exposed function with name "main"

### ISSUE THREAD

**Issue by KrystalTechnologies** [samuelhwilliams/Eel#222]
When i run my app throught the Spyder IDE, it works perfectly the first time. On the second run, i get this error:

AssertionError: Already exposed function with name "main"

My work around is to remove the @eel.expose command but then it doesn't expose any of the changes I made to the code.

Here is my code:

@eel.expose
def main(rawClientSpeech):
    return uiCompiller(rawClientSpeech)

**Comment by samuelhwilliams** [comment]
I'm not familiar with Spyder IDE, but it sounds like when the code gets executed again it's within the same Python runtime. As log as you start from a clean Python session each time, you should be fine.

This is related to https://github.com/samuelhwilliams/Eel/pull/130. I'm starting to wonder whether later calls to `eel.expose` should just overwrite previously-exposed function and log a warning that this has happened, rather than prevent it altogether...

**Comment by KrystalTechnologies** [comment]
Oh ok thank you, I tried to run the code in other IDEs and it seems to work in most of them. 

So you were right, from what I read, some IDEs use the same python environment to save on processing time.

My solution would be to write something like @feel.expose(f) (for forced) which would check if a function was already exposed and re expose it with a warning to the user. Just my two cents:)

Thanks for your help!
