### ISSUE TITLE
the port 8000 is still running after the window is closed 

### ISSUE THREAD

**Issue by chelladuraimohanraj** [samuelhwilliams/Eel#284]
**Eel version**
0.11.0.

**Describe the bug**
the port 8000 is still running after the window is closed 

i am using Ubuntu18.04 

Myprogram is
main.py:
import eel
eel.init('front')
eel.start('index.html') 
Foldername:front
index.html:
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
 
</head>

<body>
  <h1>Hello World</h1>
</body>
</html>

after i closed the window the port is still running:

![s](https://user-images.githubusercontent.com/55574199/79938054-22531180-8479-11ea-95c8-1564b514d568.png)

**Comment by Kevinrp01** [comment]
I dived pretty deep on this and still could not move past this. Some things I tried (for those the come behind me).

I (locally) modified eel/__init__.py :

- to have it's own version of GeventWebSocketServer where the server kept a reference
- to keep that server as a global
- to pass that server in as a parameter to the bottle run
- added a onclose hook that called eel.server.stop()
- confirmed the close propagated all the way to gevent._socket3.close

Looked at my netstate and **still** saw the eel port with an established connection.

So, I'm at a loss on how to proceed and expect that I will switch to calling eel in a subprocess so that I can be sure it will close the port.

**Comment by chelladuraimohanraj** [comment]
In the aspect of my project i overcame the error by the following process.

https://github.com/chelladuraimohanraj/eel-closer.git 

i think it might be helpfull

**Comment by chelladuraimohanraj** [comment]
i solved it early since i am new to github so i dont know how to request for a push on your code

**Comment by Kevinrp01** [comment]
Ah, my problem was more that the port stayed open in the same interactive session after the UI closed, so in my case I can't kill the process.

We run python as a command line interface, and so if someone starts up a 2nd shell it won't be able to display the UI (even if the first one is closed).

I think I'm going to go with copying my web app to the temp dir and randomly change the port...

**Comment by chelladuraimohanraj** [comment]
Good luck ...

**Comment by samuelhwilliams** [comment]
Glad to hear that you got to the bottom of the problem - sorry you had this issue. Try upgrading to the latest version of Eel if you continue to have difficulty with the server closing down by itself. :)
