### ISSUE TITLE
Can I prevent app from stopping when tab closes

### ISSUE THREAD

**Issue by Thoufak** [samuelhwilliams/Eel#290]
**Describe the problem**
When I close the browser tab where my app is running, the app stops. Can I keep it running, so that I can connect to the same URL later and continue using the app?

**Desktop:**
 - OS: Windows
 - Browser Chrome

**Comment by patter001** [comment]
use 

try:
   start eel
except SystemExit:
   do something

**Comment by samuelhwilliams** [comment]
It sounds a little like you want something more persistent than Eel, which by design really only runs the webserver while the browser is open. The entrypoint for the app should be launching the app - which launches a browser window - with the URL it's available on mostly not intended to be part of the end-user interface.

You could try persisting state from the app to somewhere on the filesystem so that when a user re-launches the app, it picks up from where it's left off?

**Comment by Thoufak** [comment]
@samuelhwilliams, thank you for the reply. I will consider the option you suggested :)
