### ISSUE TITLE
Switching Modes

### ISSUE THREAD

**Issue by wwderw** [samuelhwilliams/Eel#312]
I was wondering if there is an easy easy way to swap modes depending on what the program reads on the system?

For instance, I like being able to use the app mode in chrome/chromium, but for those on Firefox don't have that, but if I set the mode to custom, it doesn't do app mode at all regardless if its chrome/chromium or not.

Is there a way to handle that situation?

It's definitely a lighter weight alternative to Electron when Electron is just too heavy for some stuff.  Enjoying it thoroughly.

**Comment by samuelhwilliams** [comment]
Hi @wwderw - sorry for the slow reply.

If you set the mode to 'default' - or really any value that isn't a valid browser, then the app will launch in the system's default browser.

If you want smarter logic (i.e. try chrome, else try firefox, else try edge, else give up), which it sounds like you do, then you could code this yourself using Eel's browser modules and calling the `find_path` function in each one. If it returns a non-`None` value, then Eel thinks that browser exists.

For example, the below (note: this will only work on Windows for now, due to faulty edge detection).

```
import eel

eel.init("web")


def get_preferred_mode():
    import eel.chrome
    import eel.edge

    if eel.chrome.find_path():
        return 'chrome'
    if eel.edge.find_path():
        return 'edge'

    return 'default'

eel.start('hello.html', mode=get_preferred_mode())
```

Does this help?

**Comment by wwderw** [comment]
That was what I was looking for.  Would I be able to just swap out edge with firefox?

Let me ask you this, is it possible to go through webview using Eel?  If not, would it be possible for a future feature?  Give it more of an app like look no matter what browser was being used, while still keeping everything relatively small?

**Comment by samuelhwilliams** [comment]
Eel doesn't currently have support for Firefox - but it should be relatively easily to add. I'll see about adding it today.

WebView as in, for Android? That's not something I've considered. I'd probably need to understand the use-case better. Eel is mostly meant for quick desktop use-cases.

**Comment by samuelhwilliams** [comment]
I'll close this for now as your initial query about modes has been addressed.

Firefox support will be tracked in https://github.com/samuelhwilliams/Eel/issues/320.

Please open a new issue to discuss WebView - but my initial feeling for now is that it's not a platform we'll support. I'd be interested to gather evidence as to why I should change my mind though, so please do include your use-case and if possible share your code (if open source) so I can understand it better.
