### ISSUE TITLE
 how to prevent the app from opening simultaneously multiple times?

### ISSUE THREAD

**Issue by WMoraes13** [samuelhwilliams/Eel#324]
I would like to know if there is any way to block an app created with eel to be opened more than once simultaneously.

thanks..

**Comment by samuelhwilliams** [comment]
Hi @WMoraes13. It sounds like you want something like a pidfile. This is a file that a process writes which indicates the process is running. When starting up, check if this file exists. If it does, terminate your program because its already running. If it doesn't, then run your program.

This should be quite simple to write and this may be a good example: https://github.com/mosquito/python-pidfile

You could either use that library, or crib from the code to understand how it works, and do it yourself.

Hope this helps.

**Comment by RahulBadenkal** [comment]
I am not sure, but if you run your eel app at some specific port (say 8080 and not 0), the the os itself will block another instance of the app saying there is already an application running at the specified port.

**Comment by samuelhwilliams** [comment]
@RahulBadenkal this is probably much simpler yes - good suggestion. Silly me for not suggesting it. :)

**Comment by samuelhwilliams** [comment]
Based on the silence I'm going to close this for now. Hopefully one of the above ideas helps you @WMoraes13 :)
