### ISSUE TITLE
Eel.expose javascript not working

### ISSUE THREAD

**Issue by SoftDevDanial** [samuelhwilliams/Eel#377]
**Eel version**
0.13.2

**Describe the bug**
I tried using my javascript function in python file but it says that module eel does not have it. I have already expose the javascript function to eel as well as including <script type="text/javascript" src="/eel.js"> . However, when i use javascript to use python functions , it works. I also tried this using your example of hello_world where i just made the same exact folder as u with the exact file name and codes.(I was lazy to go find the directory where your examples were in my pc) but the same thing happened

**To Reproduce**
1. Create a function in the html file
2. Write eel.expose(func_name)
3. Write the function into the python file

**Expected behavior**
Well eel should running as per normal

**Screenshots**
My Code
![image](https://user-images.githubusercontent.com/64815604/89957481-1aa6bb00-dc6a-11ea-9b2c-508d8ccaf7e2.png)

Example Code
![image](https://user-images.githubusercontent.com/64815604/89957498-25615000-dc6a-11ea-9fe8-98d1977a6518.png)

**Desktop (please complete the following information):**
- OS
- Chrome
- Version Chrome 84.0.4147.105

**Comment by samuelhwilliams** [comment]
This isn't really a bug per se. If you run the code it will run fine. The editor, however, doesn't know that the function exists and so it's reporting that error. It's unfortunately a downside of using Eel - no IDE that I know of has support for Eel in order to correctly resolve functions across the Python-JavaScript bridge that we build. 

We'd need to look into how to provide code completion/editor hints for apps using Eel. It's not something I'm very familiar with and it's probably not something that will get addressed soon in reality - but I'll keep this open as it's an interesting thing to think about/investigate.

**Comment by SoftDevDanial** [comment]
![image](https://user-images.githubusercontent.com/64815604/89959837-eb934800-dc6f-11ea-86f6-c708fc64937c.png)
But i still cant run the hello world example

**Comment by samuelhwilliams** [comment]
How are you executing your python code? Can you share that info and the full command+traceback from the previous image snippet you showed?

It looks like you're trying to use JavaScript functions before Eel has collected them. You've got `eel.init('t')` - do you have a directory called 't'?

**Comment by SoftDevDanial** [comment]
Hi ,

I found the problem here. I like to put all my coding in one folder and into separate folders for each project im doing. So instead of t i had to put Test/t to make it work and yea the editor still thinks there's no module the function but i can still use it anyway. Like you said the ide doesn't have any support on eel which i really believe it should since this module is so useful and handy which gives modern UI while using python as its backend compared to tkinter and pyqt which in my opinion doesn't look modern and hard to style it as compared to using css and html. Thanks for the help!
