### ISSUE TITLE
Debugging with Microsoft Visual Studio Code

### ISSUE THREAD

**Issue by thewingit** [samuelhwilliams/Eel#78]
Hi all,

First of all, many thanks to @ChrisKnott for this magnificent script. It so shamelessly simple and amazingly powerful at the same time, I'm really impressed!

I tried out to make some debugging on Python side using MS Visual Studio Code (which is pretty cool and written in Electron apparently), but it doesn't seem to work.

I figured out to set up the debugger (you have to define a "launch.json" file in your root folder) so to consider the monkey patching of gevent by setting the `"gevent": true` option, but it still remains stuck as soon as it imports the eel package. This may related to some code in bottle (which has a debug=True option, by the way) but I'm really guessing at this point.

Has anyone succeeded debugging in some eel project?

Thanks in advance and have a great day.

**Comment by ChrisKnott** [comment]
@thewingit So basically I really, really didn't want to turn on monkey patching because I knew it would cause issues.

The only reason I did it was to fix an issue I was having with the [Algojammer](https://github.com/ChrisKnott/Algojammer) prototype. In retrospect this was really me abusing my position as creator of the project. Perhaps I should roll back this change. It also causes issues with IDLE.

In answer to your question, I haven't ever debugged an eel program.

**Comment by thewingit** [comment]
@ChrisKnott it was not intended as a critic all! I'm diving into this whole new world of "web-inspired" app interfaces so I'm a really newbie in this and I don't feel I should even make any suggestion of any kind. I will try with a version prior to monkey patching (the most recent one should be [0.9.8](https://github.com/ChrisKnott/Eel/tree/091038cf263e89d9bccd140dd31b60ce0cb49847)) and I'll let you know.

**Comment by brumar** [comment]
Oh ! That's why I could not use my debugger.
I think this should be rolled back or mentioned in the documentation because it's quite confusing.
I commented out this line in __init__.py, so that I could use the debugger of Pycharm.
```python
import gevent.monkey as mky; mky.patch_all()
```
But, as I just read that patching the standard library was important enough, I find another solution by setting a constant to True in a configuration file. cf:  https://blog.jetbrains.com/pycharm/2012/08/gevent-debug-support/  it seems that there is a similar solution for vscode https://code.visualstudio.com/docs/python/debugging#_gevent

**Comment by thewingit** [comment]
Thanks @brumar, I tried it out for VS code, and it works! Now I can stop both on backend and frontend side without problems. I'm using eel 0.9.7 for now, which didn't have the monkey patching already, but you said that it worked also with monkey patching turned on... It seems that attaching the debugger after the script has been launched was crucial for the debugger to work.

**Comment by brumar** [comment]
> Now I can stop both on backend and frontend side without problems
Nice ! With Pycharm CE I don't think I can ([source](https://www.jetbrains.com/help/idea/debugging-javascript-in-chrome.html)). Maybe that's time for me to try out vscode at least for debugging.
